# .github/ISSUE_TEMPLATE/setup-repository.yml
name: "Setup Unit Test Generator"
description: "Automatically configure unit test generator in your repository"
title: "Setup Unit Test Generator Request"
labels: 
  - repository-setup
assignees: 
  - "@copilot"
  - Dave-WestNeu
body:
  - type: input
    id: target_repo
    attributes:
      label: "Target Repository"
      description: "Repository to setup unit test generator"
      placeholder: "e.g., myorg/my-app"
    validations:
      required: true

  - type: input
    id: target_branch
    attributes:
      label: "Target Branch (Optional)"
      description: "Branch to create the setup PR against"
      placeholder: "Leave empty to use default branch"
      value: "main"
    validations:
      required: false

  - type: checkboxes
    id: setup_options
    attributes:
      label: "Setup Options"
      options:
        - label: "Create agent configuration file"
        - label: "Add test generation workflow"
        - label: "Configure GitHub Actions permissions"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes (Optional)"
      description: "Any special requirements or notes for the setup"
      placeholder: "e.g., Specific test frameworks, custom configurations"